/**
 * Map of country names to their flag emojis
 */
// Country code to flag image URL mapping
export const countryFlagUrls: Record<string, string> = {
  "United States": "https://flagcdn.com/w320/us.png",
  "France": "https://flagcdn.com/w320/fr.png",
  "Japan": "https://flagcdn.com/w320/jp.png",
  "United Kingdom": "https://flagcdn.com/w320/gb.png",
  "Canada": "https://flagcdn.com/w320/ca.png",
  "Germany": "https://flagcdn.com/w320/de.png",
  "Italy": "https://flagcdn.com/w320/it.png",
  "Spain": "https://flagcdn.com/w320/es.png",
  "Australia": "https://flagcdn.com/w320/au.png",
  "Brazil": "https://flagcdn.com/w320/br.png",
  "Switzerland": "https://flagcdn.com/w320/ch.png",
  "Bangladesh": "https://flagcdn.com/w320/bd.png",
  "Sweden": "https://flagcdn.com/w320/se.png",
  "Netherlands": "https://flagcdn.com/w320/nl.png",
  "Denmark": "https://flagcdn.com/w320/dk.png",
  "Norway": "https://flagcdn.com/w320/no.png",
  "Finland": "https://flagcdn.com/w320/fi.png",
  "Iceland": "https://flagcdn.com/w320/is.png",
  "Russia": "https://flagcdn.com/w320/ru.png",
  "China": "https://flagcdn.com/w320/cn.png",
  "India": "https://flagcdn.com/w320/in.png",
  "Mexico": "https://flagcdn.com/w320/mx.png",
  "South Korea": "https://flagcdn.com/w320/kr.png",
  "Ireland": "https://flagcdn.com/w320/ie.png",
  "New Zealand": "https://flagcdn.com/w320/nz.png",
  "Austria": "https://flagcdn.com/w320/at.png",
  "Belgium": "https://flagcdn.com/w320/be.png",
  "Hungary": "https://flagcdn.com/w320/hu.png",
  "Portugal": "https://flagcdn.com/w320/pt.png",
  "Colombia": "https://flagcdn.com/w320/co.png",
  "Venezuela": "https://flagcdn.com/w320/ve.png",
  "Fiji": "https://flagcdn.com/w320/fj.png",
  "Samoa": "https://flagcdn.com/w320/ws.png",
  "Argentina": "https://flagcdn.com/w320/ar.png",
  "Uruguay": "https://flagcdn.com/w320/uy.png",
  "Paraguay": "https://flagcdn.com/w320/py.png",
  "Greece": "https://flagcdn.com/w320/gr.png",
  "Turkey": "https://flagcdn.com/w320/tr.png",
  "Thailand": "https://flagcdn.com/w320/th.png",
  "South Africa": "https://flagcdn.com/w320/za.png",
  "Egypt": "https://flagcdn.com/w320/eg.png",
  "Nigeria": "https://flagcdn.com/w320/ng.png",
  "Kenya": "https://flagcdn.com/w320/ke.png",
  "Poland": "https://flagcdn.com/w320/pl.png",
  "Ukraine": "https://flagcdn.com/w320/ua.png",
  "Vietnam": "https://flagcdn.com/w320/vn.png",
  "Singapore": "https://flagcdn.com/w320/sg.png",
  "Malaysia": "https://flagcdn.com/w320/my.png",
  "Indonesia": "https://flagcdn.com/w320/id.png",
  // Additional countries for expanded world flags quiz
  "Bhutan": "https://flagcdn.com/w320/bt.png",
  "Nepal": "https://flagcdn.com/w320/np.png",
  "Tibet": "https://flagcdn.com/w320/xz.png",
  "Mongolia": "https://flagcdn.com/w320/mn.png",
  "Estonia": "https://flagcdn.com/w320/ee.png",
  "Latvia": "https://flagcdn.com/w320/lv.png",
  "Lithuania": "https://flagcdn.com/w320/lt.png",
  "Slovenia": "https://flagcdn.com/w320/si.png",
  "Slovakia": "https://flagcdn.com/w320/sk.png",
  "Serbia": "https://flagcdn.com/w320/rs.png",
  "Croatia": "https://flagcdn.com/w320/hr.png",
  "Laos": "https://flagcdn.com/w320/la.png",
  "Cambodia": "https://flagcdn.com/w320/kh.png",
  "Myanmar": "https://flagcdn.com/w320/mm.png",
  "Mauritania": "https://flagcdn.com/w320/mr.png",
  "Algeria": "https://flagcdn.com/w320/dz.png",
  "Tunisia": "https://flagcdn.com/w320/tn.png",
  "Morocco": "https://flagcdn.com/w320/ma.png",
  "Botswana": "https://flagcdn.com/w320/bw.png",
  "Namibia": "https://flagcdn.com/w320/na.png",
  "Zambia": "https://flagcdn.com/w320/zm.png",
  "Zimbabwe": "https://flagcdn.com/w320/zw.png",
  "Bahrain": "https://flagcdn.com/w320/bh.png",
  "Qatar": "https://flagcdn.com/w320/qa.png",
  "Kuwait": "https://flagcdn.com/w320/kw.png",
  "UAE": "https://flagcdn.com/w320/ae.png",
  "Brunei": "https://flagcdn.com/w320/bn.png",
  "Philippines": "https://flagcdn.com/w320/ph.png",
  "Kyrgyzstan": "https://flagcdn.com/w320/kg.png",
  "Kazakhstan": "https://flagcdn.com/w320/kz.png",
  "Uzbekistan": "https://flagcdn.com/w320/uz.png",
  "Turkmenistan": "https://flagcdn.com/w320/tm.png",
  "Moldova": "https://flagcdn.com/w320/md.png",
  "Romania": "https://flagcdn.com/w320/ro.png",
  "Bulgaria": "https://flagcdn.com/w320/bg.png",
  "Seychelles": "https://flagcdn.com/w320/sc.png",
  "Mauritius": "https://flagcdn.com/w320/mu.png",
  "Comoros": "https://flagcdn.com/w320/km.png",
  "Madagascar": "https://flagcdn.com/w320/mg.png",
  "Tonga": "https://flagcdn.com/w320/to.png",
  "Vanuatu": "https://flagcdn.com/w320/vu.png",
  "Belize": "https://flagcdn.com/w320/bz.png",
  "Guatemala": "https://flagcdn.com/w320/gt.png",
  "El Salvador": "https://flagcdn.com/w320/sv.png",
  "Honduras": "https://flagcdn.com/w320/hn.png",
  "Suriname": "https://flagcdn.com/w320/sr.png",
  "Guyana": "https://flagcdn.com/w320/gy.png",
  "French Guiana": "https://flagcdn.com/w320/gf.png",
  "Bolivia": "https://flagcdn.com/w320/bo.png",
  "Bahamas": "https://flagcdn.com/w320/bs.png",
  "Barbados": "https://flagcdn.com/w320/bb.png",
  "Jamaica": "https://flagcdn.com/w320/jm.png",
  "Trinidad and Tobago": "https://flagcdn.com/w320/tt.png",
  "Andorra": "https://flagcdn.com/w320/ad.png",
  "Monaco": "https://flagcdn.com/w320/mc.png",
  "San Marino": "https://flagcdn.com/w320/sm.png",
  "Liechtenstein": "https://flagcdn.com/w320/li.png",
  "Cyprus": "https://flagcdn.com/w320/cy.png",
  "Malta": "https://flagcdn.com/w320/mt.png",
  "Lebanon": "https://flagcdn.com/w320/lb.png",
  "Jordan": "https://flagcdn.com/w320/jo.png",
  "Gabon": "https://flagcdn.com/w320/ga.png",
  "Cameroon": "https://flagcdn.com/w320/cm.png",
  "Senegal": "https://flagcdn.com/w320/sn.png",
  "Ivory Coast": "https://flagcdn.com/w320/ci.png",
  "Malawi": "https://flagcdn.com/w320/mw.png",
  "Mozambique": "https://flagcdn.com/w320/mz.png",
  "Tanzania": "https://flagcdn.com/w320/tz.png",
  "Uganda": "https://flagcdn.com/w320/ug.png",
  "Georgia": "https://flagcdn.com/w320/ge.png",
  "Armenia": "https://flagcdn.com/w320/am.png",
  "Azerbaijan": "https://flagcdn.com/w320/az.png",
  "Albania": "https://flagcdn.com/w320/al.png",
  "North Macedonia": "https://flagcdn.com/w320/mk.png",
  "Montenegro": "https://flagcdn.com/w320/me.png",
  "Kosovo": "https://flagcdn.com/w320/xk.png",
  "Bosnia and Herzegovina": "https://flagcdn.com/w320/ba.png",
  "Luxembourg": "https://flagcdn.com/w320/lu.png",
  "Oman": "https://flagcdn.com/w320/om.png",
  "Yemen": "https://flagcdn.com/w320/ye.png",
  "Saudi Arabia": "https://flagcdn.com/w320/sa.png",
  "Equatorial Guinea": "https://flagcdn.com/w320/gq.png",
  "Guinea-Bissau": "https://flagcdn.com/w320/gw.png",
  "Guinea": "https://flagcdn.com/w320/gn.png",
  "Sierra Leone": "https://flagcdn.com/w320/sl.png",
  "Lesotho": "https://flagcdn.com/w320/ls.png",
  "Eswatini": "https://flagcdn.com/w320/sz.png",
  "Djibouti": "https://flagcdn.com/w320/dj.png",
  "Somalia": "https://flagcdn.com/w320/so.png",
  "Eritrea": "https://flagcdn.com/w320/er.png",
  "Ethiopia": "https://flagcdn.com/w320/et.png",
  "Tuvalu": "https://flagcdn.com/w320/tv.png",
  "Nauru": "https://flagcdn.com/w320/nr.png",
  "Palau": "https://flagcdn.com/w320/pw.png",
  "Marshall Islands": "https://flagcdn.com/w320/mh.png",
  "Dominica": "https://flagcdn.com/w320/dm.png",
  "Dominican Republic": "https://flagcdn.com/w320/do.png",
  "Haiti": "https://flagcdn.com/w320/ht.png",
  "Cuba": "https://flagcdn.com/w320/cu.png",
  "Panama": "https://flagcdn.com/w320/pa.png",
  "Costa Rica": "https://flagcdn.com/w320/cr.png",
  "Nicaragua": "https://flagcdn.com/w320/ni.png",
  "Ecuador": "https://flagcdn.com/w320/ec.png",
  "Peru": "https://flagcdn.com/w320/pe.png",
  "Tajikistan": "https://flagcdn.com/w320/tj.png",
  "Afghanistan": "https://flagcdn.com/w320/af.png",
  "Pakistan": "https://flagcdn.com/w320/pk.png",
  "Iran": "https://flagcdn.com/w320/ir.png",
  "Maldives": "https://flagcdn.com/w320/mv.png",
  "Sri Lanka": "https://flagcdn.com/w320/lk.png",
  "North Korea": "https://flagcdn.com/w320/kp.png",
  "Taiwan": "https://flagcdn.com/w320/tw.png",
  "Cape Verde": "https://flagcdn.com/w320/cv.png",
  "São Tomé and Príncipe": "https://flagcdn.com/w320/st.png",
  "Chad": "https://flagcdn.com/w320/td.png",
  "Mali": "https://flagcdn.com/w320/ml.png",
  "Niger": "https://flagcdn.com/w320/ne.png",
  "Burkina Faso": "https://flagcdn.com/w320/bf.png",
  "Benin": "https://flagcdn.com/w320/bj.png",
  "Togo": "https://flagcdn.com/w320/tg.png",
  "Ghana": "https://flagcdn.com/w320/gh.png",
  "Rwanda": "https://flagcdn.com/w320/rw.png",
  "Burundi": "https://flagcdn.com/w320/bi.png",
  "Democratic Republic of Congo": "https://flagcdn.com/w320/cd.png",
  "Republic of Congo": "https://flagcdn.com/w320/cg.png",
  "Angola": "https://flagcdn.com/w320/ao.png",
  "Vatican City": "https://flagcdn.com/w320/va.png",
  "Czech Republic": "https://flagcdn.com/w320/cz.png",
  "Belarus": "https://flagcdn.com/w320/by.png",
  "Iraq": "https://flagcdn.com/w320/iq.png",
  "Syria": "https://flagcdn.com/w320/sy.png",
  "Libya": "https://flagcdn.com/w320/ly.png",
  "Sudan": "https://flagcdn.com/w320/sd.png",
  "South Sudan": "https://flagcdn.com/w320/ss.png",
  "Central African Republic": "https://flagcdn.com/w320/cf.png",
  "Papua New Guinea": "https://flagcdn.com/w320/pg.png",
  "Solomon Islands": "https://flagcdn.com/w320/sb.png",
  "East Timor": "https://flagcdn.com/w320/tl.png",
  "Kiribati": "https://flagcdn.com/w320/ki.png",
  "Micronesia": "https://flagcdn.com/w320/fm.png",
  "Antigua and Barbuda": "https://flagcdn.com/w320/ag.png",
  "Saint Lucia": "https://flagcdn.com/w320/lc.png",
  "Saint Kitts and Nevis": "https://flagcdn.com/w320/kn.png",
  "Grenada": "https://flagcdn.com/w320/gd.png",
  "Chile": "https://flagcdn.com/w320/cl.png"
};

// Keep emoji flags as fallback
export const countryFlags: Record<string, string> = {
  "United States": "🇺🇸",
  "France": "🇫🇷",
  "Japan": "🇯🇵",
  "United Kingdom": "🇬🇧",
  "Canada": "🇨🇦",
  "Germany": "🇩🇪",
  "Italy": "🇮🇹",
  "Spain": "🇪🇸",
  "Australia": "🇦🇺",
  "Brazil": "🇧🇷",
  "Switzerland": "🇨🇭",
  "Bangladesh": "🇧🇩",
  "Sweden": "🇸🇪",
  "Netherlands": "🇳🇱",
  "Denmark": "🇩🇰",
  "Norway": "🇳🇴",
  "Finland": "🇫🇮",
  "Iceland": "🇮🇸",
  "Russia": "🇷🇺",
  "China": "🇨🇳",
  "India": "🇮🇳",
  "Mexico": "🇲🇽",
  "South Korea": "🇰🇷",
  "Ireland": "🇮🇪",
  "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "New Zealand": "🇳🇿",
  "Austria": "🇦🇹",
  "Belgium": "🇧🇪",
  "Hungary": "🇭🇺",
  "Portugal": "🇵🇹",
  "Colombia": "🇨🇴",
  "Venezuela": "🇻🇪",
  "Fiji": "🇫🇯",
  "Samoa": "🇼🇸",
  "Argentina": "🇦🇷",
  "Uruguay": "🇺🇾",
  "Paraguay": "🇵🇾",
  "Greece": "🇬🇷",
  "Turkey": "🇹🇷",
  "Thailand": "🇹🇭",
  "South Africa": "🇿🇦",
  "Egypt": "🇪🇬",
  "Nigeria": "🇳🇬",
  "Kenya": "🇰🇪",
  "Poland": "🇵🇱",
  "Ukraine": "🇺🇦",
  "Vietnam": "🇻🇳",
  "Singapore": "🇸🇬",
  "Malaysia": "🇲🇾",
  "Indonesia": "🇮🇩"
};

/**
 * Get flag image URL for a country name
 */
export function getFlagUrl(countryName: string): string {
  return countryFlagUrls[countryName] || "https://flagcdn.com/w320/un.png";
}

/**
 * Get flag emoji for a country name (fallback)
 */
export function getFlagEmoji(countryName: string): string {
  return countryFlags[countryName] || "🏳️";
}