import { Quiz } from "../game-store";

export const WorldFlagsQuiz: Quiz = {
  id: 'world-flags',
  title: 'World Flags Challenge',
  description: 'Test your knowledge of 50 challenging country flags from around the world',
  category: 'Geography',
  questions: [
    { id: 1, question: 'Which country does this flag belong to?', options: ['Bhutan', 'Nepal', 'Tibet', 'Mongolia'], correctAnswer: 0, timeLimit: 20 },
    { id: 2, question: 'Which country does this flag belong to?', options: ['Estonia', 'Latvia', 'Lithuania', 'Finland'], correctAnswer: 0, timeLimit: 20 },
    { id: 3, question: 'Which country does this flag belong to?', options: ['Slovenia', 'Slovakia', 'Serbia', 'Croatia'], correctAnswer: 1, timeLimit: 20 },
    { id: 4, question: 'Which country does this flag belong to?', options: ['Laos', 'Cambodia', 'Vietnam', 'Myanmar'], correctAnswer: 1, timeLimit: 20 },
    { id: 5, question: 'Which country does this flag belong to?', options: ['Mauritania', 'Algeria', 'Tunisia', 'Morocco'], correctAnswer: 3, timeLimit: 20 },
    { id: 6, question: 'Which country does this flag belong to?', options: ['Botswana', 'Namibia', 'Zambia', 'Zimbabwe'], correctAnswer: 0, timeLimit: 20 },
    { id: 7, question: 'Which country does this flag belong to?', options: ['Bahrain', 'Qatar', 'Kuwait', 'UAE'], correctAnswer: 1, timeLimit: 20 },
    { id: 8, question: 'Which country does this flag belong to?', options: ['Brunei', 'Malaysia', 'Indonesia', 'Philippines'], correctAnswer: 0, timeLimit: 20 },
    { id: 9, question: 'Which country does this flag belong to?', options: ['Kyrgyzstan', 'Kazakhstan', 'Uzbekistan', 'Turkmenistan'], correctAnswer: 2, timeLimit: 20 },
    { id: 10, question: 'Which country does this flag belong to?', options: ['Moldova', 'Romania', 'Bulgaria', 'Ukraine'], correctAnswer: 0, timeLimit: 20 },
    { id: 11, question: 'Which country does this flag belong to?', options: ['Seychelles', 'Mauritius', 'Comoros', 'Madagascar'], correctAnswer: 0, timeLimit: 20 },
    { id: 12, question: 'Which country does this flag belong to?', options: ['Tonga', 'Samoa', 'Fiji', 'Vanuatu'], correctAnswer: 2, timeLimit: 20 },
    { id: 13, question: 'Which country does this flag belong to?', options: ['Belize', 'Guatemala', 'El Salvador', 'Honduras'], correctAnswer: 0, timeLimit: 20 },
    { id: 14, question: 'Which country does this flag belong to?', options: ['Suriname', 'Guyana', 'French Guiana', 'Bolivia'], correctAnswer: 0, timeLimit: 20 },
    { id: 15, question: 'Which country does this flag belong to?', options: ['Bahamas', 'Barbados', 'Jamaica', 'Trinidad and Tobago'], correctAnswer: 3, timeLimit: 20 },
    { id: 16, question: 'Which country does this flag belong to?', options: ['Andorra', 'Monaco', 'San Marino', 'Liechtenstein'], correctAnswer: 2, timeLimit: 20 },
    { id: 17, question: 'Which country does this flag belong to?', options: ['Cyprus', 'Malta', 'Lebanon', 'Jordan'], correctAnswer: 0, timeLimit: 20 },
    { id: 18, question: 'Which country does this flag belong to?', options: ['Gabon', 'Cameroon', 'Senegal', 'Ivory Coast'], correctAnswer: 0, timeLimit: 20 },
    { id: 19, question: 'Which country does this flag belong to?', options: ['Malawi', 'Mozambique', 'Tanzania', 'Uganda'], correctAnswer: 1, timeLimit: 20 },
    { id: 20, question: 'Which country does this flag belong to?', options: ['Georgia', 'Armenia', 'Azerbaijan', 'Albania'], correctAnswer: 0, timeLimit: 20 },
    { id: 21, question: 'Which country does this flag belong to?', options: ['North Macedonia', 'Montenegro', 'Kosovo', 'Bosnia and Herzegovina'], correctAnswer: 1, timeLimit: 20 },
    { id: 22, question: 'Which country does this flag belong to?', options: ['Luxembourg', 'Netherlands', 'Belgium', 'France'], correctAnswer: 0, timeLimit: 20 },
    { id: 23, question: 'Which country does this flag belong to?', options: ['Oman', 'Yemen', 'Saudi Arabia', 'Jordan'], correctAnswer: 0, timeLimit: 20 },
    { id: 24, question: 'Which country does this flag belong to?', options: ['Equatorial Guinea', 'Guinea-Bissau', 'Guinea', 'Sierra Leone'], correctAnswer: 0, timeLimit: 20 },
    { id: 25, question: 'Which country does this flag belong to?', options: ['Lesotho', 'Eswatini', 'Botswana', 'South Africa'], correctAnswer: 1, timeLimit: 20 },
    { id: 26, question: 'Which country does this flag belong to?', options: ['Djibouti', 'Somalia', 'Eritrea', 'Ethiopia'], correctAnswer: 3, timeLimit: 20 },
    { id: 27, question: 'Which country does this flag belong to?', options: ['Tuvalu', 'Nauru', 'Palau', 'Marshall Islands'], correctAnswer: 2, timeLimit: 20 },
    { id: 28, question: 'Which country does this flag belong to?', options: ['Dominica', 'Dominican Republic', 'Haiti', 'Cuba'], correctAnswer: 0, timeLimit: 20 },
    { id: 29, question: 'Which country does this flag belong to?', options: ['Panama', 'Costa Rica', 'Nicaragua', 'Honduras'], correctAnswer: 1, timeLimit: 20 },
    { id: 30, question: 'Which country does this flag belong to?', options: ['Ecuador', 'Colombia', 'Venezuela', 'Peru'], correctAnswer: 0, timeLimit: 20 },
    { id: 31, question: 'Which country does this flag belong to?', options: ['Tajikistan', 'Afghanistan', 'Pakistan', 'Iran'], correctAnswer: 0, timeLimit: 20 },
    { id: 32, question: 'Which country does this flag belong to?', options: ['Maldives', 'Sri Lanka', 'Bangladesh', 'Nepal'], correctAnswer: 0, timeLimit: 20 },
    { id: 33, question: 'Which country does this flag belong to?', options: ['Laos', 'Cambodia', 'Thailand', 'Myanmar'], correctAnswer: 3, timeLimit: 20 },
    { id: 34, question: 'Which country does this flag belong to?', options: ['Mongolia', 'North Korea', 'South Korea', 'Taiwan'], correctAnswer: 0, timeLimit: 20 },
    { id: 35, question: 'Which country does this flag belong to?', options: ['Cape Verde', 'São Tomé and Príncipe', 'Comoros', 'Seychelles'], correctAnswer: 0, timeLimit: 20 },
    { id: 36, question: 'Which country does this flag belong to?', options: ['Chad', 'Mali', 'Niger', 'Burkina Faso'], correctAnswer: 1, timeLimit: 20 },
    { id: 37, question: 'Which country does this flag belong to?', options: ['Benin', 'Togo', 'Ghana', 'Nigeria'], correctAnswer: 0, timeLimit: 20 },
    { id: 38, question: 'Which country does this flag belong to?', options: ['Rwanda', 'Burundi', 'Democratic Republic of Congo', 'Republic of Congo'], correctAnswer: 0, timeLimit: 20 },
    { id: 39, question: 'Which country does this flag belong to?', options: ['Angola', 'Namibia', 'Zambia', 'Zimbabwe'], correctAnswer: 3, timeLimit: 20 },
    { id: 40, question: 'Which country does this flag belong to?', options: ['Vatican City', 'Monaco', 'Liechtenstein', 'Andorra'], correctAnswer: 0, timeLimit: 20 },
    { id: 41, question: 'Which country does this flag belong to?', options: ['Slovenia', 'Slovakia', 'Czech Republic', 'Croatia'], correctAnswer: 2, timeLimit: 20 },
    { id: 42, question: 'Which country does this flag belong to?', options: ['Lithuania', 'Latvia', 'Estonia', 'Belarus'], correctAnswer: 2, timeLimit: 20 },
    { id: 43, question: 'Which country does this flag belong to?', options: ['Serbia', 'Croatia', 'Bosnia and Herzegovina', 'North Macedonia'], correctAnswer: 3, timeLimit: 20 },
    { id: 44, question: 'Which country does this flag belong to?', options: ['Iraq', 'Syria', 'Jordan', 'Lebanon'], correctAnswer: 3, timeLimit: 20 },
    { id: 45, question: 'Which country does this flag belong to?', options: ['Tunisia', 'Algeria', 'Libya', 'Egypt'], correctAnswer: 2, timeLimit: 20 },
    { id: 46, question: 'Which country does this flag belong to?', options: ['Sudan', 'South Sudan', 'Central African Republic', 'Chad'], correctAnswer: 1, timeLimit: 20 },
    { id: 47, question: 'Which country does this flag belong to?', options: ['Papua New Guinea', 'Solomon Islands', 'East Timor', 'Vanuatu'], correctAnswer: 0, timeLimit: 20 },
    { id: 48, question: 'Which country does this flag belong to?', options: ['Kiribati', 'Micronesia', 'Marshall Islands', 'Tuvalu'], correctAnswer: 3, timeLimit: 20 },
    { id: 49, question: 'Which country does this flag belong to?', options: ['Antigua and Barbuda', 'Saint Lucia', 'Saint Kitts and Nevis', 'Grenada'], correctAnswer: 3, timeLimit: 20 },
    { id: 50, question: 'Which country does this flag belong to?', options: ['Paraguay', 'Bolivia', 'Chile', 'Uruguay'], correctAnswer: 0, timeLimit: 20 }
  ]
};